name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Actualiza a la versión compatible con Node.js 20

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: gedp7 acr
          resourceGroup: ${{ vars.AZURE_RG }}
          containerAppName: gedp7 containerapp
          containerAppEnvironment: gedp7 containerappenvironment